name: Custom Actions JS
on: 
    workflow_dispatch: 
    push:
env:
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
run-name: Custom Actions - JS
jobs:
    dependency-update:
        runs-on: ubuntu-latest 
        steps:      
            - name: Checkout
              uses: actions/checkout@v2
            - name: Check for dependency updates
              uses: ./.github/actions/js-dependency-update        
              with:
                  base-branch: 'main'
                  target-branch: 'update-dependencies'
                  working-directory: 'react-app'
                  gh-token: ${{ env.GH_TOKEN }}
                  debug: 'true'               